#include "../inc/ResourceManager.h"

vector <AssetResource*> ResourceManager::AllResources;

INIT_TEXTURE_RESOURCE(AdventureGetTexture)
INIT_TEXTURE_RESOURCE(AdventureHUDTexture)
INIT_TEXTURE_RESOURCE(PlayerGoombaTexture)
INIT_TEXTURE_RESOURCE(AdventureDownTexture)
INIT_TEXTURE_RESOURCE(AdventureUpTexture)
INIT_TEXTURE_RESOURCE(AdventureSideTexture)
INIT_TEXTURE_RESOURCE(PlayerGoombaTallTexture)
INIT_TEXTURE_RESOURCE(EmptyBlockSpriteTexture)
INIT_TEXTURE_RESOURCE(EmptyBlockUSpriteTexture)
INIT_TEXTURE_RESOURCE(BrickBounceSpriteTexture)
INIT_TEXTURE_RESOURCE(BrickBounceUSpriteTexture)
INIT_TEXTURE_RESOURCE(EGoombaSpriteTexture)
INIT_TEXTURE_RESOURCE(EGoombaFlagTexture)
INIT_TEXTURE_RESOURCE(CoinEffectTexture)
INIT_TEXTURE_RESOURCE(RedCoinEffectTexture)
INIT_TEXTURE_RESOURCE(BigMushroomTexture)
INIT_TEXTURE_RESOURCE(OneUpMushroomTexture)
INIT_TEXTURE_RESOURCE(MagicMushroomTexture)
INIT_TEXTURE_RESOURCE(BrickBreakTexture)
INIT_TEXTURE_RESOURCE(BrickBreakUTexture)
INIT_TEXTURE_RESOURCE(GoombaGrowTexture)
INIT_TEXTURE_RESOURCE(GoombaDuckTexture)
INIT_TEXTURE_RESOURCE(FlowerTexture)
INIT_TEXTURE_RESOURCE(FireTexture)
INIT_TEXTURE_RESOURCE(ExplosionTexture)
INIT_TEXTURE_RESOURCE(TurtleTexture)
INIT_TEXTURE_RESOURCE(TurtleShellTexture)
INIT_TEXTURE_RESOURCE(IceBreakTexture)
INIT_TEXTURE_RESOURCE(StarTexture)
INIT_TEXTURE_RESOURCE(PlayerGoombaDeadTexture)
INIT_TEXTURE_RESOURCE(FlagPoleTexture)
INIT_TEXTURE_RESOURCE(SecretFlagPoleTexture)
INIT_TEXTURE_RESOURCE(FlagTexture)
INIT_TEXTURE_RESOURCE(SecretFlagTexture)
INIT_TEXTURE_RESOURCE(PlayerFlagTexture)
INIT_TEXTURE_RESOURCE(EventBoxTexture)
INIT_TEXTURE_RESOURCE(PlantTexture)
INIT_TEXTURE_RESOURCE(BulletTexture)
INIT_TEXTURE_RESOURCE(GuyTexture)
INIT_TEXTURE_RESOURCE(PlotDeviceTexture)
INIT_TEXTURE_RESOURCE(AdventureTriangleTexture)
INIT_TEXTURE_RESOURCE(SunTexture)
INIT_TEXTURE_RESOURCE(SpriteSpawnTexture)
INIT_TEXTURE_RESOURCE(OldManTexture)
INIT_TEXTURE_RESOURCE(AdventureFireTexture)
INIT_TEXTURE_RESOURCE(AdventureSwordTexture)
INIT_TEXTURE_RESOURCE(AdventureAttackUpTexture)
INIT_TEXTURE_RESOURCE(AdventureAttackDownTexture)
INIT_TEXTURE_RESOURCE(AdventureAttackSideTexture)
INIT_TEXTURE_RESOURCE(AdventureDoorCloseTexture)
INIT_TEXTURE_RESOURCE(OktoTexture);
INIT_TEXTURE_RESOURCE(OktoSideTexture);
INIT_TEXTURE_RESOURCE(OktoEyesTexture);

INIT_ANIMATION_RESOURCE(OktoAnimation)
INIT_ANIMATION_RESOURCE(OktoSideAnimation)
INIT_ANIMATION_RESOURCE(AdventureDoorCloseAnimation)
INIT_ANIMATION_RESOURCE(AdventureDoorOpenAnimation)
INIT_ANIMATION_RESOURCE(AdventureAttackSideAnimation)
INIT_ANIMATION_RESOURCE(AdventureAttackDownAnimation)
INIT_ANIMATION_RESOURCE(AdventureAttackUpAnimation)
INIT_ANIMATION_RESOURCE(AdventureFireAnimation)
INIT_ANIMATION_RESOURCE(SpriteSpawnAnimation)
INIT_ANIMATION_RESOURCE(PlayerGoombaAnimation)
INIT_ANIMATION_RESOURCE(AdventureDownAnimation)
INIT_ANIMATION_RESOURCE(AdventureUpAnimation)
INIT_ANIMATION_RESOURCE(AdventureSideAnimation)
INIT_ANIMATION_RESOURCE(PlayerGoombaTallAnimation)
INIT_ANIMATION_RESOURCE(EmptyBlockSpriteAnimation);
INIT_ANIMATION_RESOURCE(EmptyBlockUSpriteAnimation);
INIT_ANIMATION_RESOURCE(BrickBounceSpriteAnimation);
INIT_ANIMATION_RESOURCE(BrickBounceUSpriteAnimation);
INIT_ANIMATION_RESOURCE(EGoombaAnimation)
INIT_ANIMATION_RESOURCE(CoinEffectAnimation)
INIT_ANIMATION_RESOURCE(RedCoinEffectAnimation)
INIT_ANIMATION_RESOURCE(BrickBreakAnimation)
INIT_ANIMATION_RESOURCE(BrickBreakUAnimation)
INIT_ANIMATION_RESOURCE(GoombaGrowAnimation)
INIT_ANIMATION_RESOURCE(GoombaDuckAnimation)
INIT_ANIMATION_RESOURCE(FlowerAnimation)
INIT_ANIMATION_RESOURCE(FireAnimation)
INIT_ANIMATION_RESOURCE(ExplosionAnimation)
INIT_ANIMATION_RESOURCE(TurtleAnimation)
INIT_ANIMATION_RESOURCE(StarAnimation)
INIT_ANIMATION_RESOURCE(GoombaShrinkAnimation)
INIT_ANIMATION_RESOURCE(FireworkAnimation)
INIT_ANIMATION_RESOURCE(PlantAnimation)
INIT_ANIMATION_RESOURCE(IceBreakAnimation)
INIT_ANIMATION_RESOURCE(SunAnimation)

ResourceManager::ResourceManager()
{
	
}

ResourceManager::~ResourceManager()
{
	for (int i = 0; i < AllResources.size(); i++)
	{
		if (AllResources[i])
		{
			delete AllResources[i];
			AllResources[i] = NULL;
		}
	}
}
